"""centralized prompts and models for the research agent system"""

from .clarification import CLARIFICATION_PROMPT
from .classification import CLASSIFICATION_PROMPT, QUERY_CLASSIFIER_PROMPT
from .evaluators import BALANCE_PROMPT, CITATION_PROMPT, GROUNDEDNESS_PROMPT
from .followup import FOLLOWUP_FINAL_PROMPT, FOLLOWUP_SYSTEM_PROMPT
from .models import (
    CLARIFICATION_MODEL,
    CLASSIFICATION_MODEL,
    EVALUATOR_MODEL,
    FOLLOWUP_MODEL,
    SUB_RESEARCH_MODEL,
    SUB_RESEARCH_TOOL_MODEL,
    SUPERVISOR_MODEL,
    SYNTHESIS_MODEL,
    ModelConfig,
    Models,
)
from .sub_research import (
    ANGLE_DESCRIPTIONS,
    DRAFT_SYNTHESIS_PROMPT,
    SUB_RESEARCH_SYSTEM_PROMPT,
)
from .supervisor import SUPERVISOR_INITIAL_PROMPT, SUPERVISOR_REVIEW_PROMPT
from .synthesis import (
    QUALITY_CHECK_PROMPT,
    SYNTHESIS_FROM_DRAFTS_PROMPT,
    SYNTHESIS_PROMPT,
)

PROMPT_VERSION = "1.0.0"

__all__ = [
    "PROMPT_VERSION",
    "CLARIFICATION_PROMPT",
    "CLASSIFICATION_PROMPT",
    "QUERY_CLASSIFIER_PROMPT",
    "SUPERVISOR_INITIAL_PROMPT",
    "SUPERVISOR_REVIEW_PROMPT",
    "SUB_RESEARCH_SYSTEM_PROMPT",
    "DRAFT_SYNTHESIS_PROMPT",
    "ANGLE_DESCRIPTIONS",
    "SYNTHESIS_FROM_DRAFTS_PROMPT",
    "SYNTHESIS_PROMPT",
    "QUALITY_CHECK_PROMPT",
    "FOLLOWUP_SYSTEM_PROMPT",
    "FOLLOWUP_FINAL_PROMPT",
    "BALANCE_PROMPT",
    "GROUNDEDNESS_PROMPT",
    "CITATION_PROMPT",
    "ModelConfig",
    "Models",
    "CLARIFICATION_MODEL",
    "CLASSIFICATION_MODEL",
    "SUPERVISOR_MODEL",
    "SUB_RESEARCH_MODEL",
    "SUB_RESEARCH_TOOL_MODEL",
    "SYNTHESIS_MODEL",
    "FOLLOWUP_MODEL",
    "EVALUATOR_MODEL",
]
