import re


def extract_keywords(query: str, max_keywords: int = 5) -> str:
    stopwords = {
        "the",
        "a",
        "an",
        "and",
        "or",
        "but",
        "in",
        "on",
        "at",
        "to",
        "for",
        "of",
        "with",
        "by",
        "from",
        "as",
        "is",
        "was",
        "are",
        "were",
        "been",
        "be",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "should",
        "could",
        "may",
        "might",
        "must",
        "can",
        "his",
        "her",
        "their",
        "its",
        "this",
        "that",
        "these",
        "those",
        "what",
        "which",
        "who",
        "when",
        "where",
        "why",
        "how",
        "about",
        "into",
        "through",
        "during",
        "before",
        "after",
        "above",
        "below",
        "between",
        "under",
        "over",
        "latest",
        "recent",
        "term",
        "terms",
        "success",
        "failure",
    }
    words = re.findall(r"\b[a-zA-Z]+\b", query.lower())
    keywords = [w for w in words if w not in stopwords and len(w) > 2]
    return " ".join(keywords[:max_keywords])


def simplify_query_for_rss(query: str) -> list[str]:
    keywords = extract_keywords(query, max_keywords=10)
    return [w for w in keywords.split() if len(w) >= 4]
